version: "3"
services:
  node-app:
    image: node:22
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    command: yarn start # or npm start
