name: Run Node.js with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and run Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose exec node-app yarn test # or npm test

      - name: Shut down Docker Compose
        run: docker-compose down
